### ISSUE TITLE
http://wikitrivia.atbaker.me is not available any more ?

### ISSUE THREAD

**Issue by bgoutham** [atbaker/wikipedia-question-generator#1]
Andrew:  Very interesting project, I was hoping to play with it at the above link. Seems no longer available?

**Comment by sivasivacsc** [comment]
Am also interested in this project but the thing is same issue

**Comment by atbaker** [comment]
Hi guys - apologies for the late reply.

I'm not interested in maintaining this project anymore, but it's MIT licensed so you can do pretty much anything you want with it.

I'll add a note to the README now.
