### ISSUE TITLE
Why there is text restriction?

### ISSUE THREAD

**Issue by JafferWilson** [atbaker/wikipedia-question-generator#2]
I have tried some edition to the code and have give the complete text file as input instead of the program fetching it from the wikipedia.   
But I am getting the follwing error:  

> Traceback (most recent call last):
>   File "C:\myquestions\questansgen-script.py", line 11, in <module>
>     load_entry_point('questansgen==0.1', 'console_scripts', 'questansgen')()
>   File "c:\Python36\lib\site-packages\click\core.py", line 610, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\Python36\lib\site-packages\click\core.py", line 590, in main
>     rv = self.invoke(ctx)
>   File "c:\Python36\lib\site-packages\click\core.py", line 782, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\Python36\lib\site-packages\click\core.py", line 416, in invoke
>     return callback(*args, **kwargs)
>   File "C:\myquestions\questansgen\scripts\questansgen.py", line 22, in generate_trivia
>     questions = questions + article.generate_trivia_sentences()
>   File "C:\myquestions\questansgen\article.py", line 22, in generate_trivia_sentences
>     trivia = self.evaluate_sentence(sentence)
>   File "C:\myquestions\questansgen\article.py", line 100, in evaluate_sentence
>     trivia['similar_words'] = self.get_similar_words(replace_nouns[0])
>   File "C:\myquestions\questansgen\article.py", line 39, in get_similar_words
>     hypernym = synset.hypernyms()[0]
> IndexError: list index out of range

How I can resolve it please explain?

**Comment by atbaker** [comment]
Hi Jaffer.

I'm not interested in maintaining this project anymore, but it's MIT licensed so you can do pretty much anything you want with it.

I'll add a note to the README now.
